version: '3.8'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reviewmate
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
  myapp:
    build:
      context: .
      # dockerﬁle: "Dockerﬁle"
    ports:
      - "9001:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: NovoRoot!@12
